version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # Exposing this for external DB clients for your convenience
      - '5432:5432'
volumes:
  pgdata: {}
