# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous integration

on:
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    env:
      SKIP_DEV_SEED: true
      DATABASE_URL: postgresql://postgres:test@localhost:5432/db

    strategy:
      matrix:
        node-version: [17.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
        # Wait until Postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: 🧶 Generate code
        run: npm run codegen

      - name: 🔨 Compile
        run: npm run ts

      - name: ⚙ Test
        run: npm run test

      - name: Set up database
        run: npm prisma-reset

      - name: 🎰 Integration test
        run: npm run itest
